#!/usr/bin/env bash
# a Bash script that will display information about the subdomains

#dns_config () {
#    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
#    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
#}

#if [ "$#" == 1 ]
#then
#  dns_config "$1" "www"
#  dns_config "$1" "lb-01"
#  dns_config "$1" "web-01"
#  dns_config "$1" "web-02"
#elif [ "$#" == 2 ]
#then
#  dns_config "$1" "$2"
#fi

#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

runDig () {
    subarg=$1
    urlarg=$2

    dig "$subarg.$urlarg" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subarg" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

allSubs=( "www" "lb-01" "web-01" "web-02" )

if [ $# -eq 1 ]; then
    url="$1"
    for s in "${allSubs[@]}"
    do
	runDig "$s" "$url"
    done
elif [ $# -eq 2 ]; then
    url="$1"
    sub="$2"
    runDig "$sub" "$url"
fi
