#!/usr/bin/env bash
# debugging nginx (service (init) must say that nginx is not running)
# sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
# service nginx restart
# pkill -o nginx
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm /var/run/nginx.pid
