#!/usr/bin/env bash
# A script that prints best school 10 times

n=1
while [ $n -le 10 ]
do
    echo "Best School"
    (( n++))
done
# I=0
# while [ $I -lt 10 ]
# do 
# 	echo "Best School"
# 	I=$((I + 1))
