#!/usr/bin/env bash
# A script that displays Best School 10 times

n=1
until [ $n -gt 10 ]
do
    echo "Best School"
    ((n++))
done

# I=0
# until [ $I -gt 9 ]
# do
# 	echo "Best School"
# 	I=$((I + 1))
# done
