#!/usr/bin/env bash
# A bash script that displays Best School 10 times
#    but after the 9th iteration display Best School then Hi on new line

n=1

while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n -eq 9 ]
    then
        echo "Hi"
    fi
    ((n++))
done
