#!/usr/bin/env bash
# A bash script that displays the current directory in a list format
#     where only the part of the name afte rthe first dash is displayed
#     using for loop but do not display hidden files

for i in $mylist; do
    echo "$i" | cut -d '-' -f2
done
