#!/usr/bin/env bash
# This script displays all active IPv4 addresses on the machine
# ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 6-
# ifconfig | grep 'inet addr' | cut -d':' -f2 | cut -d' ' -f1
# ifconfig | grep -Po 'inet \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | cut -d " " -f2
# ifconfig | grep "inet " | awk '{print $2}'

# ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 6-

ifconfig -a | grep inet | cut -d: -f2 | cut -d" "  -f1
