#!/usr/bin/env bash

# Connect to your server using the private key ~/.ssh/school with the user ubuntu
ssh -i ~/.ssh/school ubuntu@34.73.76.135

# Connect to another server using the same key
ssh -i ~/.ssh/school ubuntu@3.86.7.131
